Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/advent_2018/day_03.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/advent_2018/day_03.rb'